### ISSUE TITLE
Add a Location Question Type

### ISSUE THREAD

**Issue by davegautam** [alexitaylor/ng-surveys#4]
It would be better to add a Location Question that will allow users to pick a specific location.  This Question in Display would open a map (google or other) where user can search a place and select a place. The Location Data along with Long and Lat Will be Recorded.

**Comment by alexitaylor** [comment]
@davegautam 

This feature would require to use 3rd party libraries and I would like to steer away from depending on too many outside packages. Whenever we add dependency we are increasing the overhead for our end user. Already our users have to install a handful of peer-dependencies which is not ideal. 

Rather I forsee the users having the ability to create their own custom questions, such as your Location Question, and the library being able to dynamically render those custom question components. This allows the end user to add 3rd party libraries at their own digression. While this may create more work for the end user it does lead to a more flexible experience of the library.  

In order to accomplish this feature, we would add to the `option` input property of `NgBuilderViewerComponent` with a defined prop similar to this:

```
interface ICustomQuestion extends IQuestion {
    //...	
    code: string;
}
```

Then by using a [Dynamic Component Loader](https://angular.io/guide/dynamic-component-loader) we can render custom question components from the user. The library is already dynamically loading question components (found under `projects/ng-surveys/src/lib/builder/question-builder` directory), but it will have to be adjusted to handle user-created components. Also, a service will have to be created in order for the 3 main library components (`NgBuilderViewerComponent`, `NgModelViewerComponent` and `NgSurveyViewerComponent`) to easily share and manage the user, created component.

With that said you can fork this project and add your location question, but you may run the risk of it not being merged back into master as I want to reduce the number of peer-dependencies for the user.

**Comment by davegautam** [comment]
@alexitaylor I like your idea about the same. maybe I will fork the project and start working on something as you said. will be in communication.
